[build]
builder = "nixpacks"

[build.environment]
NODE_ENV = "production"
NPM_CONFIG_OPTIONAL = "false"
NPM_CONFIG_OMIT = "optional"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
NPM_CONFIG_IGNORE_SCRIPTS = "true"
NPM_CONFIG_IGNORE_ENGINES = "true"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health/simple"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 